databases:
  - name: chessata_db
    plan: free
    databaseName: chessata_db
    user: chessata_django

services:
  - type: web
    plan: free
    name: chessata_django
    runtime: python
    buildCommand: "./django_build.sh"
    startCommand: "cd src/web/chess_web; daphne --port 10000 --bind 0.0.0.0 chess_web.asgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: chessata_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4