# Generated by Django 5.0.7 on 2024-09-13 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameLobby',
            fields=[
                ('game_code', models.TextField(max_length=50, primary_key=True, serialize=False)),
                ('is_over', models.BooleanField(default=False)),
                ('has_started', models.BooleanField(default=False)),
                ('is_white_turn', models.BooleanField(default=True)),
                ('board', models.JSONField()),
                ('allow_en_passant', models.JSONField()),
                ('has_king_moved', models.JSONField()),
                ('has_rook_moved', models.JSONField()),
                ('match_state', models.TextField(default='not over', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ChessUser',
            fields=[
                ('user_id', models.TextField(max_length=64, primary_key=True, serialize=False)),
                ('username', models.TextField(max_length=64)),
                ('color', models.TextField(max_length=30)),
                ('game_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='chess_api.gamelobby')),
            ],
        ),
    ]
