# Generated by Django 5.0.7 on 2024-09-06 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChessUser',
            fields=[
                ('user_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=16)),
                ('game_code', models.CharField(max_length=6)),
                ('color', models.CharField(max_length=30)),
            ],
        ),
    ]
