# Generated by Django 5.0.6 on 2024-09-09 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameLobby',
            fields=[
                ('game_code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('is_over', models.BooleanField(default=False)),
                ('is_white_turn', models.BooleanField(default=True)),
                ('board', models.JSONField()),
                ('allow_en_passant', models.JSONField()),
                ('has_king_moved', models.JSONField()),
                ('has_rook_moved', models.JSONField()),
            ],
        ),
        migrations.AlterField(
            model_name='chessuser',
            name='game_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='chess_api.gamelobby'),
        ),
    ]
