# Generated by Django 5.0.6 on 2024-09-09 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_api', '0002_gamelobby_alter_chessuser_game_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamelobby',
            name='match_state',
            field=models.CharField(default='not over', max_length=30),
        ),
    ]
