# Generated by Django 5.0.7 on 2024-09-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_api', '0003_gamelobby_match_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamelobby',
            name='has_started',
            field=models.BooleanField(default=False),
        ),
    ]
